# This file is a part of the UMSKT Project
#
# Copyleft (C) 2019-2023 UMSKT Contributors (et.al.)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# @FileCreated by TheTank20 on 06/13/2023
# @Maintainer Neo

name: C/C++ CI (Windows)

on:
  push:
    branches: [ "*" ]
    paths-ignore: [ '**.md', 'doc/**', '.idea/**']
  workflow_dispatch:

jobs:
  build-tdm64:
    runs-on: windows-latest
    steps:

      - name: Setup TDM-GCC
        run: |
          Write-Host Downloading TDM-GCC v10.3.0...
          Invoke-WebRequest -Uri 'https://github.com/jmeubank/tdm-gcc/releases/download/v10.3.0-tdm64-2/tdm64-gcc-10.3.0-2.exe' -OutFile 'C:\Windows\temp\TDM-GCC-64.exe'
          Write-Host Creating directory...
          New-Item -ItemType Directory -Path 'C:\TDM-GCC-64'
          Write-Host Copying files [Set 1/3]...
          Start-Process '7z' -ArgumentList 'e C:\Windows\temp\TDM-GCC-64.exe -oC:\TDM-GCC-64 -y' -Wait
          Write-Host Copying files [Set 2/3]...
          Start-Process '7z' -ArgumentList 'e C:\TDM-GCC-64\*.tar.xz -oC:\TDM-GCC-64 -y' -Wait
          Write-Host Copying files [Set 3/3]...
          Start-Process '7z' -ArgumentList 'x C:\TDM-GCC-64\*.tar -oC:\TDM-GCC-64 -y' -Wait
          Write-Host Adding environment variables...
          $env:PATH = 'C:\TDM-GCC-64\bin;' + $env:PATH
          [Environment]::SetEnvironmentVariable('PATH', $env:PATH, [EnvironmentVariableTarget]::Machine)

      - name: Checkout Source Tree
        uses: actions/checkout@v4

      - name: Download OpenSSL-TDM-64 release asset
        shell: pwsh
        run: |
          $url = "https://github.com/UMSKT/winactiontest/releases/download/openssl/OpenSSL-TDM-64.zip"
          Invoke-WebRequest -Uri $url -OutFile "OpenSSL-TDM-64.zip"
          Expand-Archive -Path "OpenSSL-TDM-64.zip" -DestinationPath "$env:GITHUB_WORKSPACE"

      - name: Configure UMSKT (TDM-GCC 64-bit)
        shell: pwsh
        run: |
          $env:PATH = 'C:\TDM-GCC-64\bin;' + $env:PATH
          $OPENSSL_ROOT = "$env:GITHUB_WORKSPACE/OpenSSL-TDM-64"
          $OPENSSL_LIB = "$OPENSSL_ROOT/lib64"
          $OPENSSL_INC = "$OPENSSL_ROOT/include"
          cmake -G "MinGW Makefiles" `
            -DCMAKE_C_COMPILER="gcc" `
            -DCMAKE_CXX_COMPILER="g++" `
            -DOPENSSL_ROOT_DIR="$OPENSSL_ROOT" `
            -DOPENSSL_INCLUDE_DIR="$OPENSSL_INC" `
            -DOPENSSL_CRYPTO_LIBRARY="$OPENSSL_LIB/libcrypto.a" `
            -DOPENSSL_SSL_LIBRARY="$OPENSSL_LIB/libssl.a" `
            -DCMAKE_C_FLAGS="-m64" `
            -DCMAKE_CXX_FLAGS="-m64" `
            .

      - name: Build UMSKT (TDM-GCC 64-bit)
        shell: pwsh
        run: |
          $env:PATH = 'C:\TDM-GCC-64\bin;' + $env:PATH
          mingw32-make

      - name: Upload build artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: UMSKT-TDM64
          path: ./Release/*

# 32-bit support will happen when everything's all good
